config/routes.rb
CmpcLabDelta::Application.routes.draw do
  resources :companies

  resources :accounts

  resources :expenses

  get 'apis/quickbooks/:action', :controller => 'qbwc', :as => 'quickbooks'
  resources :form607s

  resources :fiscal_reports
  root to: 'fiscal_reports#index'

  devise_for :users

  

end

app/models/fiscal_report.rb
class FiscalReport < ActiveRecord::Base
end

app/controllers/fiscal_reports_controller.rb
class FiscalReportsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /results
  # GET /results.json
  def index
    @fiscal_reports = FiscalReport.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @fiscal_report = FiscalReport.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @fiscal_report = FiscalReport.new(fiscal_report_params)

    respond_to do |format|
      if @fiscal_report.save
        format.html { redirect_to @fiscal_report, notice: 'Result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fiscal_report }
      else
        format.html { render action: 'new' }
        format.json { render json: @fiscal_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @fiscal_report.update(result_params)
        format.html { redirect_to @fiscal_report, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fiscal_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @fiscal_report.destroy
    respond_to do |format|
      format.html { redirect_to fiscal_reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @fiscal_report = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:fiscal_report).permit(:patient, :age, :gender)
    end
end

app/views/fiscal_reports/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient %><br>
    <%= f.text_field :patient %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiscal_reports/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/fiscal_reports/index.html.erb
<!--Content-->
<section id="page-title">
  <div class="container">
    <div class="row">
      <div class="span12 text-center">
        <h3>Panel de Control</h3>
      </div>
    </div>
  </div>
</section>
  
 
<!--Work-->
<section id="content2">

  <div class="container text-center">

		<a class="btn btn-lg btn-main" href="#">
		  <i class="fa fa-bars fa-3x pull-left"></i> 
		 FORM 606</a>


		<a class="btn btn-lg btn-main" href="#">
		  <i class="fa fa-bars fa-3x pull-left"></i> 
		 FORM 607</a>


		<a class="btn btn-lg btn-main" href="#">
		  <i class="fa fa-money fa-3x pull-left"></i> 
		 CHEQUES</a>


		<a class="btn btn-lg btn-main" href="#"><i class="fa fa-usd fa-3x pull-left"></i>RECIBOS</a>
	          
      
    			
    		
    		</div><!--End Row of Work-->
      
  </div>
</section>          

    
<!--Twitter Feed-->
<section id="twitter">
  <div class="container">
    <div class="row">
      <div class="span12 text-center">
        <i class="icon-twitter icon-4x gray margin-20"></i>
          <div class="twitter-feed">
  					<ul id="twitter_update_list" class="rotate"></ul>
  				</div>
      </div>
    </div>
  </div>
</section>


<h1>Listing results</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Age</th>
      <th>Gender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fiscal_reports.each do |report| %>
      <tr>
        <td><%= result.patient %></td>
        <td><%= result.age %></td>
        <td><%= result.gender %></td>
        <td><%= link_to 'Show', fiscal_report %></td>
        <td><%= link_to 'Edit', edit_fiscal_report_path(report) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_fiscal_report_path %>

app/views/fiscal_reports/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/fiscal_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @result.patient %>
</p>

<p>
  <strong>Age:</strong>
  <%= @result.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @result.gender %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>