config/routes.rb
CmpcLabDelta::Application.routes.draw do
  resources :companies

  resources :accounts

  resources :expenses

  get 'apis/quickbooks/:action', :controller => 'qbwc', :as => 'quickbooks'
  resources :form607s

  resources :fiscal_reports
  root to: 'fiscal_reports#index'

  devise_for :users

  

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json

  def index
    @products = Product.order(:name)
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end


  def index
    @expenses = Expense.all
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls
    end
    
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:line, :businessid, :typeid, :account_id, :ncf, :modified_document, :voucher_date, :payment_date, :billed_itbis, :retained_itbis, :amount_billed, :retained_isr, :status)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<!--Content-->
<section id="page-title">
  <div class="container">
    <div class="row">
      <div class="span12 text-center">
        <h3>Formulario 606</h3>
      </div>
    </div>
	 </div>
</section>

					    <!--Content-->
					    <section>
					      <div class="container">
					        <div class="row">
					          <div class="span12 text-center">

											<div class="span2 text-left">
											</div>
											
											<div class="span2 text-left">
											</div>
											
											<div class="span3 text-left">
											</div>



					          </div>
					        </div>
								 </div>
					    </section>
                  
	                <!-- table sample -->
	                <!-- the script for the toggle all checkboxes from header is located in js/theme.js -->
 
                 <div class="table-products section">
	                    <div class="row-fluid head">
	                        <div class="span12">
	                            <h4>Products</h4>
	                        </div>
	                    </div>


	                    <div class="row-fluid">
	                        <table class="table table-hover">
	                            <thead>
	                                <tr>
                                 		<th class="span3">RNC o Cédula</th>
                                    <th class="span3">Tipo ID</th>
                                    <th class="span4">Cuentas</th>
                                    <th class="span3">NCF</th>
                                    <th class="span3">Documento Modificado</th>
                                    <th class="span3">Fecha Comprobante</th>
                                    <th class="span3">Fecha de pago</th>
                                    <th class="span3">ITBIS facturado</th>
                                    <th class="span3">ITBIS Retenido</th>
                                    <th class="span3">Monto Facturado</th>
                                    <th class="span3">ISR Retenido</th>
                                    <th class="span3"><span class="line"></span>Status</th>
	                                </tr>
	                            </thead>
	                            <tbody>
	                                <!-- row --> 
																	<%= form_for(@expense) do |f| %>
																	<% if @expense.errors.any? %>
																    <div id="error_explanation">
																      <h2><%= pluralize(@expense.errors.count, "error") %>
																					prohibited this company from being saved:</h2>
																      <ul>
																      <% @expense.errors.full_messages.each do |msg| %>
																        <li><%= msg %></li>
																      <% end %>
																      </ul>
																    </div>
																  <% end %>
																  	
	                                <tr class="first">
	                                    <td><%= f.number_field :businessid %></td>
	                                    <td><%= f.number_field :typeid %></td>
	                                    <td><%= f.number_field :account_id %></td>
	                                    <td><%= f.text_field :ncf %></td>
	                                    <td><%= f.text_field :modified_document %></td>
	                                    <td><%= f.date_select :voucher_date %></td>
	                                    <td><%= f.date_select :payment_date %></td>
	                                    <td><%= f.text_field :billed_itbis %></td>
	                                    <td><%= f.text_field :retained_itbis %></td>
	                                    <td><%= f.text_field :billed_itbis %></td>
	                                    <td><%= f.text_field :retained_isr %></td>
	                                    <td><span class="label label-info">Standby</span></td>

	                                </tr>
																    <%= f.submit %>
																  
																	<% end %>
	                                <!-- row -->
	                            </tbody>
	                        </table>
	                    </div>

    <div class="pagination">
      <ul>
        <li><a href="#">&#8249;</a></li>
        <li><a class="active" href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">&#8250;</a></li>
      </ul>
		</div>
			
    </div>
</div>

<hr>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<!--Content-->
<section id="page-title">
  <div class="container">
    <div class="row">
      <div class="span12 text-center">
        <h3>Formulario 606</h3>
      </div>
    </div>
	 </div>
</section>

					    <!--Content-->
					    <section>
					      <div class="container">
					        <div class="row">
					          <div class="span12 text-center">

											<div class="span2 text-left">
											</div>
											
											<div class="span2 text-left">
											</div>
											
											<div class="span3 text-left">
											</div>



					          </div>
					        </div>
								 </div>
					    </section>
                  
	                <!-- table sample -->
	                <!-- the script for the toggle all checkboxes from header is located in js/theme.js -->
 
                 <div class="table-products section">
	                    <div class="row-fluid head">
	                        <div class="span12">
	                            <h4>Products</h4>
	                        </div>
	                    </div>


	                    <div class="row-fluid">
	                        <table class="table table-hover">
	                            <thead>
	                                <tr>
                                   		<th class="span2">RNC o Cédula</th>
	                                    <th class="span2">Tipo ID</th>
	                                    <th class="span4">Cuentas</th>
	                                    <th class="span2">NCF</th>
	                                    <th class="span2">Documento Modificado</th>
	                                    <th class="span1">Fecha Comprobante</th>
	                                    <th class="span1">Fecha de pago</th>
	                                    <th class="span2">ITBIS facturado</th>
	                                    <th class="span2">ITBIS Retenido</th>
	                                    <th class="span2">Monto Facturado</th>
	                                    <th class="span2">ISR Retenido</th>
	                                    <th class="span2"><span class="line"></span>Status</th>
	                                </tr>
	                            </thead>
	                            <tbody>
	                                <!-- row -->
																	<% @expenses.each do |expense| %>
	                                <tr class="first">
														        <td><%= expense.businessid %></td>
														        <td><%= expense.typeid %></td>
														        <td><%= expense.account_id %></td>
														        <td><%= expense.ncf %></td>
														        <td><%= expense.modified_document %></td>
														        <td><%= expense.voucher_date %></td>
														        <td><%= expense.payment_date %></td>
														        <td><%= expense.billed_itbis %></td>
														        <td><%= expense.retained_itbis %></td>
														        <td><%= expense.amount_billed %></td>
														        <td><%= expense.retained_isr %></td>
	                                  <td><span class="label label-info"><%= expense.status %></span></td>
	                                </tr>
	                                <% end %>
																  <!-- row -->
	                            </tbody>
	                        </table>
	                    </div>

    <div class="pagination">
      <ul>
        <li><a href="#">&#8249;</a></li>
        <li><a class="active" href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">&#8250;</a></li>
      </ul>
		</div>
			
    </div>
</div>
<div class="row">
	
</div>

app/views/expenses/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Línea</Data></Cell>
        <Cell><Data ss:Type="String">RNC o Cédula</Data></Cell>
        <Cell><Data ss:Type="String">Tipo ID</Data></Cell>
        <Cell><Data ss:Type="String">Tipo bienes y servicios comprados</Data></Cell>
        <Cell><Data ss:Type="String">NCF</Data></Cell>
        <Cell><Data ss:Type="String">NCF o Documento Modificado</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de comprobante</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de pago</Data></Cell>
        <Cell><Data ss:Type="String">Itbis facturado</Data></Cell>
        <Cell><Data ss:Type="String">Itbis retenido</Data></Cell>
        <Cell><Data ss:Type="String">Monto facturado</Data></Cell>
        <Cell><Data ss:Type="String">Retención renta</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>
	    <%= @expenses.each do |expense| %>
      <Row>
        <Cell><Data ss:Type="String"><%= expense.line %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.businessid %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.typeid %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.account_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.ncf %>NCF</Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.modified_document %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.voucher_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.payment_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.billed_itbis %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.retained_itbis %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.amount_billed %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.retained_isr %></Data></Cell>
        <Cell><Data ss:Type="String"><%= expense.status %></Data></Cell>
      </Row>
			<% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @expense.line %>
</p>

<p>
  <strong>Businessid:</strong>
  <%= @expense.businessid %>
</p>

<p>
  <strong>Typeid:</strong>
  <%= @expense.typeid %>
</p>

<p>
  <strong>Account:</strong>
  <%= @expense.account_id %>
</p>

<p>
  <strong>Ncf:</strong>
  <%= @expense.ncf %>
</p>

<p>
  <strong>Modified document:</strong>
  <%= @expense.modified_document %>
</p>

<p>
  <strong>Voucher date:</strong>
  <%= @expense.voucher_date %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @expense.payment_date %>
</p>

<p>
  <strong>Billed itbis:</strong>
  <%= @expense.billed_itbis %>
</p>

<p>
  <strong>Retained itbis:</strong>
  <%= @expense.retained_itbis %>
</p>

<p>
  <strong>Amount billed:</strong>
  <%= @expense.amount_billed %>
</p>

<p>
  <strong>Retained isr:</strong>
  <%= @expense.retained_isr %>
</p>

<p>
  <strong>Status:</strong>
  <%= @expense.status %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>